[workspace]
members = [
  "zkit",
  "zkvm",
  "plonky",
  "starky",
  "algebraic",
  "groth16",
  "dsl_compile"
]
resolver = "2"

[patch."https://github.com/0xEigenLabs/eigen-zkvm"]
plonky = { path = "plonky" }
starky = { path = "starky" }
