[package]
name = "zkvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
# serialization
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
mktemp = "0.5.1"
log = "0.4.0"

compiler = { git = "https://github.com/powdr-labs/powdr.git", branch = "main", package = "compiler" }
riscv = { git = "https://github.com/powdr-labs/powdr.git", branch = "main", package = "riscv" }
number = { git = "https://github.com/powdr-labs/powdr.git", branch = "main", package = "number" }
backend = { git = "https://github.com/powdr-labs/powdr.git", branch = "main", package = "backend" }

revm = { git = "https://github.com/bluealloy/revm", features = ["std", "ethersdb", "serde"] }

[dev-dependencies]
env_logger = "0.10"
hex = "0.4.3"
indicatif = "*"
ethers-providers = { version = "2.0", features = ["ws"] }
ethers-core = { version = "2.0" }
tokio = { version = "1.35", features = [
    "rt-multi-thread",
    "macros",
] }
futures = { version = "0.3.30" }
