[package]
name = "starky"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"

winterfell = { version="0.4", default-features = false, features = ["concurrent"] }
winter-prover = { version="0.4", default-features = false, features = ["concurrent"] }
winter-air = { version="0.4", default-features = false }
winter-utils = { version = "0.4", package = "winter-utils", default-features = false, features = ["concurrent"] }
rand-utils = { version = "0.4", package = "winter-rand-utils" }
winter-math = { version = "0.4" , features = ["concurrent"] }
winter-crypto = { version = "0.4" , features = ["concurrent"] }

serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"

# Hash
ff = {package="ff_ce" , version="0.11", features = ["derive"]}
rand = "0.4"
lazy_static = "1.0"


thiserror="1.0"

[dev-dependencies]
