[package]
name = "starky"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"

winterfell = { version="0.4", default-features = false }
core-utils = { version = "0.4", package = "winter-utils", default-features = false }
rand-utils = { version = "0.4", package = "winter-rand-utils" }
winter-math = { version = "0.4" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rand =  { version = "0.8" }
thiserror="1.0"

[dev-dependencies]
